version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "redis_server"
    ports:
      - "6379:6379"
    networks:
      - app_network

  postgres:
    image: "postgres:latest"
    container_name: "postgres_server"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: advertisement
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: 