// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	query "github.com/truongtu268/distributePriorityQueue/db/query"
)

// AdCreateQuery is an autogenerated mock type for the AdCreateQuery type
type AdCreateQuery struct {
	mock.Mock
}

// CreateAd provides a mock function with given fields: ctx, arg
func (_m *AdCreateQuery) CreateAd(ctx context.Context, arg query.CreateAdParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateAd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, query.CreateAdParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdCreateQuery creates a new instance of AdCreateQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdCreateQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdCreateQuery {
	mock := &AdCreateQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
