// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	query "github.com/truongtu268/distributePriorityQueue/db/query"
)

// AdGetQuery is an autogenerated mock type for the AdGetQuery type
type AdGetQuery struct {
	mock.Mock
}

// GetAdByID provides a mock function with given fields: ctx, id
func (_m *AdGetQuery) GetAdByID(ctx context.Context, id string) (query.Ad, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAdByID")
	}

	var r0 query.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (query.Ad, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) query.Ad); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(query.Ad)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAdGetQuery creates a new instance of AdGetQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdGetQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdGetQuery {
	mock := &AdGetQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
