// Code generated by mockery v2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	query "github.com/truongtu268/distributePriorityQueue/db/query"
)

// MockAdCreateQuery is an autogenerated mock type for the AdCreateQuery type
type MockAdCreateQuery struct {
	mock.Mock
}

// CreateAd provides a mock function with given fields: ctx, arg
func (_m *MockAdCreateQuery) CreateAd(ctx context.Context, arg query.CreateAdParams) error {
	ret := _m.Called(ctx, arg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, query.CreateAdParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
