// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/truongtu268/distributePriorityQueue/model"

	query "github.com/truongtu268/distributePriorityQueue/db/query"
)

// IAdCronjobRepo is an autogenerated mock type for the IAdCronjobRepo type
type IAdCronjobRepo struct {
	mock.Mock
}

// AddAdAnalysis provides a mock function with given fields: ctx, adID, analysis
func (_m *IAdCronjobRepo) AddAdAnalysis(ctx context.Context, adID string, analysis model.AdAnalysis) error {
	ret := _m.Called(ctx, adID, analysis)

	if len(ret) == 0 {
		panic("no return value specified for AddAdAnalysis")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.AdAnalysis) error); ok {
		r0 = rf(ctx, adID, analysis)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAdByID provides a mock function with given fields: ctx, adID
func (_m *IAdCronjobRepo) GetAdByID(ctx context.Context, adID string) (query.Ad, error) {
	ret := _m.Called(ctx, adID)

	if len(ret) == 0 {
		panic("no return value specified for GetAdByID")
	}

	var r0 query.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (query.Ad, error)); ok {
		return rf(ctx, adID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) query.Ad); ok {
		r0 = rf(ctx, adID)
	} else {
		r0 = ret.Get(0).(query.Ad)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, adID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessTask provides a mock function with given fields: ctx, adID
func (_m *IAdCronjobRepo) ProcessTask(ctx context.Context, adID string) error {
	ret := _m.Called(ctx, adID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, adID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RetryAd provides a mock function with given fields: ctx, adID, retryTime
func (_m *IAdCronjobRepo) RetryAd(ctx context.Context, adID string, retryTime int32) error {
	ret := _m.Called(ctx, adID, retryTime)

	if len(ret) == 0 {
		panic("no return value specified for RetryAd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32) error); ok {
		r0 = rf(ctx, adID, retryTime)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAdCronjobRepo creates a new instance of IAdCronjobRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdCronjobRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdCronjobRepo {
	mock := &IAdCronjobRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
