// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IAdQueueRepo is an autogenerated mock type for the IAdQueueRepo type
type IAdQueueRepo struct {
	mock.Mock
}

// UpdateAdStatus provides a mock function with given fields: ctx, adID
func (_m *IAdQueueRepo) UpdateAdStatus(ctx context.Context, adID string) error {
	ret := _m.Called(ctx, adID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAdStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, adID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAdQueueRepo creates a new instance of IAdQueueRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAdQueueRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAdQueueRepo {
	mock := &IAdQueueRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
