// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	model "github.com/truongtu268/distributePriorityQueue/model"
)

// ICreateAdRepo is an autogenerated mock type for the ICreateAdRepo type
type ICreateAdRepo struct {
	mock.Mock
}

// CreateAd provides a mock function with given fields: ctx, dto
func (_m *ICreateAdRepo) CreateAd(ctx context.Context, dto model.AdRequest) error {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for CreateAd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AdRequest) error); ok {
		r0 = rf(ctx, dto)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICreateAdRepo creates a new instance of ICreateAdRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICreateAdRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICreateAdRepo {
	mock := &ICreateAdRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
